modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="enchantable"
version="1.1.0"
displayName="Enchantable"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/enchantable/update.json"
displayURL="https://mrcrayfish.com/minimods"
logoFile=""
credits=""
authors="MrCrayfish"
description="Adds new balanced enchantments that extend improve the vanilla game"

[[dependencies.enchantable]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.90,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"