modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"

[[mods]]
modId="enchantable"
version="1.4.1"
displayName="Enchantable"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=enchantable"
displayURL="https://mrcrayfish.com/mods?id=enchantable"
logoFile="enchantable_logo.png"
authors="MrCrayfish"
description="Enchantable is a mod that brings new and balanced enchantments to the game! It expands on aspects of the game where no vanilla enchantments provides benifits but also adds new functionality to existing gameplay. The enchantments are designed to not be overpowered to keep the vanilla feel. Currently Enchantable adds four new enchantments but more will be added over time!"

[[dependencies.enchantable]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[modproperties.enchantable]
    catalogueImageIcon="enchantable_icon.png"
    configuredBackground="minecraft:textures/block/spruce_planks.png"
