modLoader="javafml"
loaderVersion="[34,)"
license="All Rights Reserved"

[[mods]]
modId="enchantable"
version="1.4.0"
displayName="Enchantable"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/enchantable/update.json"
displayURL="https://mrcrayfish.com/minimods"
logoFile="enchantable.png"
#credits=""
authors="MrCrayfish"
description="Adds new balanced enchantments that extend improve the vanilla game"
itemIcon="minecraft:enchanted_book"
configBackground="minecraft:textures/block/spruce_planks.png"

[[dependencies.enchantable]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
