modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="enchantable"
version="1.3.0"
displayName="Enchantable"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/MiniMods/enchantable/update.json"
displayURL="https://mrcrayfish.com/minimods"
#logoFile=""
#credits=""
authors="MrCrayfish"
description="Adds new balanced enchantments that extend improve the vanilla game"

[[dependencies.enchantable]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"